### ISSUE TITLE
Jacktook stopped working after update to Jackett Version v0.24.243

### ISSUE THREAD

**Issue by sasiccia84** [Sam-Max/plugin.video.jacktook#140]
Hi! 

Jacktook stopped working after update to Jackett Version v0.24.243 

I was wondering if you would please help me solving this issue,

Thanks a lot!

Kind Regards,

S.

**Comment by Sam-Max** [comment]
Fixed on b07b80d664b821d6c206f72b9144e1704608a247

**Comment by sasiccia84** [comment]
Hi! Thanks a lot for the reply :)


I've downloaded
https://github.com/Sam-Max/plugin.video.jacktook/archive/b07b80d664b821d6c206f72b9144e1704608a247.zip

and installed it in my kodi on my Android TV but the issue persists,


Can you please help?

Thanks a lot!

Kind regards,

S.
